import { promises as fs } from "fs";
import path from "path";
import grayMatter from "gray-matter";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>lucky copper books</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>lucky copper 瑞铜 books</h1>

        <p className={styles.description}>
          i am a student who likes reading books--mainly young adult fiction{" "}
          <br /> (i am trying my best to branch out to adult fiction as well
          though!).
        </p>

        <div className={styles.grid}>
          {posts.map((post) => {
            const { cover_url, title, path, date } = post;
            console.log(cover_url);
            return (
              <Link key={path} href={path}>
                <a className={styles.card}>
                  <Image width={532} height={800} alt={title} src={cover_url} />
                  <h3>{title}</h3>
                  <p>{date}</p>
                </a>
              </Link>
            );
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        Made with 💚 using Next.js and MDX
      </footer>
    </div>
  );
}

export async function getStaticProps() {
  const postsDirectory = path.join(process.cwd(), "pages/posts");
  const filenames = await fs.readdir(postsDirectory);

  const files = await Promise.all(
    filenames
      .sort()
      .reverse()
      .map(async (filename) => {
        const filePath = path.join(postsDirectory, filename);
        const content = await fs.readFile(filePath, "utf8");
        const matter = grayMatter(content);
        return {
          filename,
          matter,
        };
      })
  );

  const posts = files.map((file) => {
    console.log(file.matter.data);
    return {
      path: `/posts/${file.filename.replace(".mdx", "")}`,
      title: file.matter.data.title,
      date: file.matter.data.date,
      cover_url: file.matter.data.cover_url,
    };
  });

  return {
    props: {
      posts,
    },
  };
}

/*
how to add an image to mdx:
  import Image from "next/image";

  This is my first post!

  <Image
    width={500}
    height={500}
    src="https://www.nasa.gov/sites/default/files/1-bluemarble_west.jpg"
  />

  npm run dev
*/
